[package]
name = "livestream-build"
version = "0.1.0"
edition = "2024"

[dependencies]
gstreamer = "0.24.4"
gstreamer-webrtc = "0.24.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
